export const CREATE_TASK = 'CREATE_TASK'

export const REQUEST_TASKS_PENDING = 'REQUEST_TASKS_PENDING'
export const REQUEST_TASKS_SUCCESS = 'REQUEST_TASKS_SUCCESS'
export const REQUEST_TASKS_FAILED = 'REQUEST_TASKS_FAILED'