export const API_URL = 'https://5d6e4e17777f670014036633.mockapi.io/tasks'
export const CREATE_TASK = 'CREATE_TASK'

export const REQUEST_TASKS_PENDING = 'REQUEST_TASKS_PENDING'
export const REQUEST_TASKS_SUCCESS = 'REQUEST_TASKS_SUCCESS'
export const REQUEST_TASKS_FAILED = 'REQUEST_TASKS_FAILED'